spring:
  application:
    name: springcommerce
  # Dados de Conexão com o banco H2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  # Configuração do Cliente web do banco H2
  h2:
    console:
      enabled: true
      path: /h2-console
  # Configuração para mostrar o SQL no console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true